customhost = "employee.cxwfusms7e6g.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "phoonwenhao-employee"
customfolder = "employee-image"
customregion = "us-east-1"